import { uiDataPackage, type UiRaceStoryRef } from './uiDataPackage';
import { packModules, packRawModules } from './packModules';

/** Race-story packs: full-field lap chart, inflection moments, field-strength
 *  read, teammates, and section strengths for one completed race. Generated by
 *  scripts/build-ui-data-package.mjs into analysis/race-story/output/context-packs/
 *  and loaded here with sha256 integrity against the package refs. */

export interface RaceStoryLapDriver {
  driverId: string;
  driverName: string;
  carNumber: string | null;
  isBryce: boolean;
  isTeammate: boolean;
  finishPosition: number | null;
  status: string | null;
  laps: Array<[number, number]>;
}

export interface RaceStoryInflection {
  lap: number;
  fromPosition: number | null;
  toPosition: number;
  delta: number | null;
  trigger: string;
  cautionState: string;
}

export interface RaceStoryPack {
  schemaVersion: string;
  type: 'race_story';
  id: string;
  sessionId: string;
  raceLabel: string;
  seasonYear: number | null;
  track: { name?: string; type?: string } | null;
  lapChart: {
    totalLaps: number;
    fieldSize: number;
    sourceState: string;
    drivers: RaceStoryLapDriver[];
  };
  bryce: {
    inLapChart: boolean;
    lapsCompleted: number | null;
    startPosition: number | null;
    finishPosition: number | null;
    status: string | null;
  };
  inflections: RaceStoryInflection[];
  weekendSignal: {
    bestPracticeRank: number | null;
    bestQualifyingRank: number | null;
    raceStart: number | null;
    raceFinish: number | null;
    caveat: string;
  } | null;
  fieldStrength: {
    ratedRivals: number | null;
    mean: number | null;
    median: number | null;
    topRated: Array<{ name: string; rating: number }>;
    bryceFinishPercentile: number | null;
    resultVsFieldStrength: number | null;
    seasonDepthRank: { rank: number; of: number } | null;
    sourceState: string;
    caveat: string;
  } | null;
  teammates: Array<{
    driverName: string;
    carNumber: string | null;
    isBryce: boolean;
    finishPosition: number | null;
    startPosition: number | null;
    status: string | null;
  }>;
  teamContext: { teamName: string; teamCars: number | null; teamAverageFinish: number | null; statusCaveat: string } | null;
  sections: {
    comparisonRows: number | null;
    medianPercentile: number | null;
    best: Array<{ name: string; percentile: number }>;
    weakest: Array<{ name: string; percentile: number }>;
    sourceState: string;
    caveat: string;
  } | null;
  pointsImpact: {
    racePoints: number | null;
    cumulativePoints: number | null;
    standingAfter: number | null;
    standingBefore: number | null;
    pointsBehindLeader: number | null;
    leaderDriver: string | null;
  } | null;
  sourceRefs: Array<{ key: string; path: string; note: string }>;
  caveats: string[];
}

const sha256Hex = async (value: string): Promise<string> => {
  const bytes = new TextEncoder().encode(value);
  const digest = await globalThis.crypto.subtle.digest('SHA-256', bytes);
  return Array.from(new Uint8Array(digest))
    .map((byte) => byte.toString(16).padStart(2, '0'))
    .join('');
};

const storyRefFor = (sessionId: string): UiRaceStoryRef | null =>
  (uiDataPackage.screens.raceDebrief.raceStoryRefs ?? []).find((ref) => ref.sessionId === sessionId) ?? null;

const cache = new Map<string, Promise<RaceStoryPack | null>>();

export const loadRaceStory = (sessionId: string): Promise<RaceStoryPack | null> => {
  const existing = cache.get(sessionId);
  if (existing) return existing;
  const promise = (async (): Promise<RaceStoryPack | null> => {
    const ref = storyRefFor(sessionId);
    if (!ref) return null;
    const key = `../../${ref.path}`;
    const jsonLoader = packModules[key];
    const rawLoader = packRawModules[key];
    if (!jsonLoader || !rawLoader) return null;
    const pack = ((await jsonLoader()) as { default: RaceStoryPack }).default;
    const rawText = (await rawLoader()) as string;
    if ((await sha256Hex(rawText)) !== ref.sha256 || pack.id !== ref.id || pack.sessionId !== sessionId) {
      throw new Error(`Race-story pack integrity mismatch: ${ref.path}`);
    }
    return pack;
  })();
  cache.set(sessionId, promise);
  return promise;
};
