import { uiDataPackage, type UiRaceStoryRef } from './uiDataPackage';
import { packUrls } from './packModules';
import { loadContextPack } from './packLoader';

/** Race-story packs: full-field lap chart, inflection moments, field-strength
 *  read, teammates, and section strengths for one completed race. Generated by
 *  scripts/build-ui-data-package.mjs into analysis/race-story/output/context-packs/
 *  and loaded here with sha256 integrity against the package refs. */

export interface RaceStoryLapDriver {
  driverId: string;
  driverName: string;
  carNumber: string | null;
  isBryce: boolean;
  isTeammate: boolean;
  finishPosition: number | null;
  status: string | null;
  laps: Array<[number, number]>;
}

export interface RaceStoryInflection {
  lap: number;
  fromPosition: number | null;
  toPosition: number;
  delta: number | null;
  trigger: string;
  cautionState: string;
}

/** One restart: the caution period it followed, the green-lap window measured,
 *  and the full field's movement with Bryce inside it. `precision` marks the
 *  source grain so per-second data can later refine the same shape unchanged. */
export interface RestartEvent {
  restartIndex: number | null;
  restartLap: number | null;
  baselineLap: number | null;
  windowLaps: number | null;
  windowEndLap: number | null;
  fullWindow: boolean;
  cautionReasons: string | null;
  precision: 'lap-chart';
  field: {
    classified: number | null;
    medianNet: number | null;
    bestNet: number | null;
  };
  bryce: {
    baselinePosition: number | null;
    restartPosition: number | null;
    endPosition: number | null;
    net: number | null;
    rankInField: number | null;
    fieldSize: number | null;
  } | null;
}

export interface RaceStoryRestarts {
  detected: number;
  cautionPeriods: number;
  windowLaps: number;
  precision: 'lap-chart';
  /** '' | 'no_cautions' | 'cautions_ended_under_yellow' — why there is no restart to show. */
  noRestartReason: string;
  bryce: {
    counted: number;
    net: number;
    gained: number;
    held: number;
    slipped: number;
    rankInField: number | null;
    fieldSizeRanked: number | null;
    soleBestInField: boolean;
    coBestInField: boolean;
  };
  coverageNote: string;
  events: RestartEvent[];
  caveat: string;
}

export interface RaceStoryCautionEvent {
  cautionNumber: number | null;
  startLap: number | null;
  endLap: number | null;
  durationLaps: number | null;
  restartLap: number | null;
  ranToFlag: boolean;
  /** 'opening' | 'middle' | 'final' | 'unknown' — which third of the race it fell in. */
  third: string;
  /** Grouped official cause: Contact | Off course | Spin | Debris | Mechanical | Conditions. */
  category: string;
}

/** The per-race caution line for "The day": counts of official caution episodes,
 *  never lap times or positions. `precision: 'official-report'` today; a
 *  per-second source could later refine the same shape with no UI rework. */
export interface RaceStoryCautions {
  precision: 'official-report';
  count: number;
  lapsUnderYellow: number;
  totalRaceLaps: number | null;
  thirds: { opening: number; middle: number; final: number };
  categories: Array<{ category: string; count: number }>;
  events: RaceStoryCautionEvent[];
  caveat: string;
}

export interface RaceStoryPack {
  schemaVersion: string;
  type: 'race_story';
  id: string;
  sessionId: string;
  raceLabel: string;
  seasonYear: number | null;
  track: { name?: string; type?: string } | null;
  lapChart: {
    totalLaps: number;
    fieldSize: number;
    sourceState: string;
    drivers: RaceStoryLapDriver[];
  };
  bryce: {
    inLapChart: boolean;
    lapsCompleted: number | null;
    startPosition: number | null;
    finishPosition: number | null;
    status: string | null;
  };
  inflections: RaceStoryInflection[];
  restarts: RaceStoryRestarts | null;
  cautions: RaceStoryCautions | null;
  battles: Array<{
    driverName: string;
    carNumber: string | null;
    isTeammate: boolean;
    lapsAdjacent: number;
    swaps: number;
  }>;
  weather: {
    ambientTempC: number | null;
    windSpeedKph: number | null;
    windGustKph: number | null;
    humidityPct: number | null;
    precipitationMm: number | null;
    conditionRaw: string | null;
    source: string | null;
    caveat: string;
  } | null;
  weekendSignal: {
    bestPracticeRank: number | null;
    bestQualifyingRank: number | null;
    raceStart: number | null;
    raceFinish: number | null;
    caveat: string;
  } | null;
  fieldStrength: {
    ratedRivals: number | null;
    mean: number | null;
    median: number | null;
    topRated: Array<{ name: string; rating: number }>;
    bryceFinishPercentile: number | null;
    resultVsFieldStrength: number | null;
    seasonDepthRank: { rank: number; of: number } | null;
    sourceState: string;
    caveat: string;
  } | null;
  teammates: Array<{
    driverName: string;
    carNumber: string | null;
    isBryce: boolean;
    finishPosition: number | null;
    startPosition: number | null;
    status: string | null;
  }>;
  teamContext: { teamName: string; teamCars: number | null; teamAverageFinish: number | null; statusCaveat: string } | null;
  sections: {
    comparisonRows: number | null;
    medianPercentile: number | null;
    best: Array<{ name: string; percentile: number }>;
    weakest: Array<{ name: string; percentile: number }>;
    sourceState: string;
    caveat: string;
  } | null;
  pointsImpact: {
    racePoints: number | null;
    cumulativePoints: number | null;
    standingAfter: number | null;
    standingBefore: number | null;
    pointsBehindLeader: number | null;
    leaderDriver: string | null;
  } | null;
  sourceRefs: Array<{ key: string; path: string; note: string }>;
  caveats: string[];
}

const storyRefFor = (sessionId: string): UiRaceStoryRef | null =>
  (uiDataPackage.screens.raceDebrief.raceStoryRefs ?? []).find((ref) => ref.sessionId === sessionId) ?? null;

const cache = new Map<string, Promise<RaceStoryPack | null>>();

export const loadRaceStory = (sessionId: string): Promise<RaceStoryPack | null> => {
  const existing = cache.get(sessionId);
  if (existing) return existing;
  const promise = (async (): Promise<RaceStoryPack | null> => {
    const ref = storyRefFor(sessionId);
    if (!ref) return null;
    const key = `../../${ref.path}`;
    const loaded = await loadContextPack<RaceStoryPack>(packUrls, key);
    if (!loaded) return null;
    const { data: pack, sha256 } = loaded;
    if (sha256 !== ref.sha256 || pack.id !== ref.id || pack.sessionId !== sessionId) {
      throw new Error(`Race-story pack integrity mismatch: ${ref.path}`);
    }
    return pack;
  })();
  cache.set(sessionId, promise);
  return promise;
};
