import { trackOutlineFor } from '../assets/tracks';
import { uiDataPackage, type UiSectionLapRef } from './uiDataPackage';
import { packUrls } from './packModules';
import { loadContextPack } from './packLoader';
import type { SectionSourceTier } from './sectionObservations';

/** Section-lap packs (Brief H — Section Intelligence): Bryce's per-lap,
 *  per-section observations from official Section Results, one pack per race.
 *  Generated by scripts/build-ui-data-package.mjs into
 *  analysis/race-story/output/context-packs/ and loaded here with sha256
 *  integrity against the package refs — the traceable substrate behind the
 *  heat map's lap scopes and the "why" drawer. */

/** Tuple order matches the pack's tupleOrder field:
 *  [lap, fieldPercentile, fieldRank, fieldComparisonCount, clean(0|1),
 *   caution('g'|'c'|'r'|'u'), timeSeconds, speedMph] */
export type SectionLapTuple = [
  number | null,
  number | null,
  number | null,
  number | null,
  0 | 1,
  'g' | 'c' | 'r' | 'u',
  number | null,
  number | null
];

export interface SectionLapsPack {
  schemaVersion: string;
  type: 'section_laps';
  id: string;
  sessionId: string;
  raceLabel: string;
  seasonYear: number | null;
  venueName: string;
  trackType: string | null;
  totalLaps: number;
  tupleOrder: string[];
  /** Which source fed this pack. Absent/`parsed_pdf_aggregate` = the official
   *  Section Results parse (v1, the fallback path). `lake_loop_crossings` = the
   *  RaceTools race-weekend capture's timing-loop crossings (the measured
   *  upgrade: fine sub-sections tiling the whole lap). The producer reads this
   *  to label the tier in the set it emits — same contract, richer source. */
  sourceTier?: SectionSourceTier;
  /** Qualifying packs compare each driver's best clean time in each section
   * inside Bryce's actual qualifying group. Those best sections need not come
   * from one lap, so the UI names this basis explicitly instead of implying a
   * whole-lap comparison. Race packs omit this field. */
  comparisonScope?: 'qualifying_group_best_sections';
  sections: Array<{
    sectionName: string;
    /** 'measured' = a real timing-loop section; 'derived_remainder' = the
     *  untimed stretch(es) shaded from lap time minus the timed sections. */
    kind?: 'measured' | 'derived_remainder';
    laps: SectionLapTuple[];
    /** Each field car's median clean-lap section time (seconds) for the whole
     *  race — the quiet field distribution behind Bryce's marker in the drawer.
     *  Absent when the source carries no field-time distribution. */
    fieldSeconds?: number[];
  }>;
  /** Whether this race carries a genuine untimed stretch worth a derived shade
   *  ('genuine_gap') or its racing sections tile the lap ('fully_timed'). */
  derivedCoverage?: 'genuine_gap' | 'fully_timed' | null;
  lapTotals: SectionLapTuple[];
  sourceStateCounts: Record<string, number>;
  sourceRefs: Array<{ key: string; path: string; note: string }>;
  caveats: string[];
}

const refs = (): UiSectionLapRef[] => uiDataPackage.screens.raceDebrief.sectionLapRefs ?? [];

const refFor = (sessionId: string): UiSectionLapRef | null =>
  refs().find((ref) => ref.sessionId === sessionId) ?? null;

/** All race visits with per-lap section data at a venue (for the YoY shapes),
 *  oldest first. Metadata only — nothing loads until loadSectionLaps. */
/** One venue, one name: result feeds call two street venues by their event
 *  names ("Detroit Downtown Street Circuit") while the section packs carry the
 *  asset names ("Streets of Detroit"). Compare through the outline's canonical
 *  name so no caller has to remember to alias first. */
const canonicalVenue = (name: string | null | undefined): string | null =>
  name ? trackOutlineFor(name)?.name ?? name : null;

export const sectionLapVisitsFor = (venueName: string | null | undefined): UiSectionLapRef[] => {
  if (!venueName) return [];
  const venue = canonicalVenue(venueName);
  const canonicalOrder = new Map(
    (uiDataPackage.screens.raceDebrief.seasonIndex ?? [])
      .filter((row) => canonicalVenue(row.trackName) === venue)
      .sort(
        (left, right) =>
          (left.raceDate ?? left.eventStartDate ?? '').localeCompare(right.raceDate ?? right.eventStartDate ?? '') ||
          (left.roundIndex ?? 0) - (right.roundIndex ?? 0) ||
          left.sessionId.localeCompare(right.sessionId)
      )
      .map((row, index) => [row.sessionId, index])
  );
  return refs()
    .filter((ref) => canonicalVenue(ref.venueName) === venue)
    .sort(
      (left, right) =>
        (canonicalOrder.get(left.sessionId) ?? Number.MAX_SAFE_INTEGER) -
          (canonicalOrder.get(right.sessionId) ?? Number.MAX_SAFE_INTEGER) ||
        (left.seasonYear ?? 0) - (right.seasonYear ?? 0) ||
        left.sessionId.localeCompare(right.sessionId)
    );
};

const cache = new Map<string, Promise<SectionLapsPack | null>>();

/** `priority` (Fetch Priority Hints) only takes effect on the FIRST call for a
 *  given sessionId — the one that actually creates the cached fetch; a second
 *  caller just gets that same in-flight/resolved promise. `useVenueSectionData`
 *  uses this to mark the venue page's selected visit `'high'` among the batch
 *  of visits it loads concurrently, so that pack — the one actually about to
 *  render — wins the race on a constrained connection instead of finishing
 *  whenever it happens to among several equal-priority requests. */
export const loadSectionLaps = (sessionId: string, priority?: RequestPriority): Promise<SectionLapsPack | null> => {
  const existing = cache.get(sessionId);
  if (existing) return existing;
  const promise = (async (): Promise<SectionLapsPack | null> => {
    const ref = refFor(sessionId);
    if (!ref) return null;
    const key = `../../${ref.path}`;
    const loaded = await loadContextPack<SectionLapsPack>(packUrls, key, priority);
    if (!loaded) return null;
    const { data: pack, sha256 } = loaded;
    if (sha256 !== ref.sha256 || pack.id !== ref.id || pack.sessionId !== sessionId) {
      throw new Error(`Section-lap pack integrity mismatch: ${ref.path}`);
    }
    return pack;
  })();
  cache.set(sessionId, promise);
  return promise;
};
