import { uiDataPackage, type UiSectionLapRef } from './uiDataPackage';
import { packModules, packRawModules } from './packModules';
import type { SectionSourceTier } from './sectionObservations';

/** Section-lap packs (Brief H — Section Intelligence): Bryce's per-lap,
 *  per-section observations from official Section Results, one pack per race.
 *  Generated by scripts/build-ui-data-package.mjs into
 *  analysis/race-story/output/context-packs/ and loaded here with sha256
 *  integrity against the package refs — the traceable substrate behind the
 *  heat map's lap scopes and the "why" drawer. */

/** Tuple order matches the pack's tupleOrder field:
 *  [lap, fieldPercentile, fieldRank, fieldComparisonCount, clean(0|1),
 *   caution('g'|'c'|'r'|'u'), timeSeconds, speedMph] */
export type SectionLapTuple = [
  number | null,
  number | null,
  number | null,
  number | null,
  0 | 1,
  'g' | 'c' | 'r' | 'u',
  number | null,
  number | null
];

export interface SectionLapsPack {
  schemaVersion: string;
  type: 'section_laps';
  id: string;
  sessionId: string;
  raceLabel: string;
  seasonYear: number | null;
  venueName: string;
  trackType: string | null;
  totalLaps: number;
  tupleOrder: string[];
  /** Which source fed this pack. Absent/`parsed_pdf_aggregate` = the official
   *  Section Results parse (v1, the fallback path). `lake_loop_crossings` = the
   *  RaceTools race-weekend capture's timing-loop crossings (the measured
   *  upgrade: fine sub-sections tiling the whole lap). The producer reads this
   *  to label the tier in the set it emits — same contract, richer source. */
  sourceTier?: SectionSourceTier;
  sections: Array<{
    sectionName: string;
    /** 'measured' = a real timing-loop section; 'derived_remainder' = the
     *  untimed stretch(es) shaded from lap time minus the timed sections. */
    kind?: 'measured' | 'derived_remainder';
    laps: SectionLapTuple[];
    /** Each field car's median clean-lap section time (seconds) for the whole
     *  race — the quiet field distribution behind Bryce's marker in the drawer.
     *  Absent when the source carries no field-time distribution. */
    fieldSeconds?: number[];
  }>;
  /** Whether this race carries a genuine untimed stretch worth a derived shade
   *  ('genuine_gap') or its racing sections tile the lap ('fully_timed'). */
  derivedCoverage?: 'genuine_gap' | 'fully_timed' | null;
  lapTotals: SectionLapTuple[];
  sourceStateCounts: Record<string, number>;
  sourceRefs: Array<{ key: string; path: string; note: string }>;
  caveats: string[];
}

const sha256Hex = async (value: string): Promise<string> => {
  const bytes = new TextEncoder().encode(value);
  const digest = await globalThis.crypto.subtle.digest('SHA-256', bytes);
  return Array.from(new Uint8Array(digest))
    .map((byte) => byte.toString(16).padStart(2, '0'))
    .join('');
};

const refs = (): UiSectionLapRef[] => uiDataPackage.screens.raceDebrief.sectionLapRefs ?? [];

const refFor = (sessionId: string): UiSectionLapRef | null =>
  refs().find((ref) => ref.sessionId === sessionId) ?? null;

/** All race visits with per-lap section data at a venue (for the YoY shapes),
 *  oldest first. Metadata only — nothing loads until loadSectionLaps. */
export const sectionLapVisitsFor = (venueName: string | null | undefined): UiSectionLapRef[] => {
  if (!venueName) return [];
  return refs()
    .filter((ref) => ref.venueName === venueName)
    .sort((left, right) => (left.seasonYear ?? 0) - (right.seasonYear ?? 0) || left.sessionId.localeCompare(right.sessionId));
};

const cache = new Map<string, Promise<SectionLapsPack | null>>();

export const loadSectionLaps = (sessionId: string): Promise<SectionLapsPack | null> => {
  const existing = cache.get(sessionId);
  if (existing) return existing;
  const promise = (async (): Promise<SectionLapsPack | null> => {
    const ref = refFor(sessionId);
    if (!ref) return null;
    const key = `../../${ref.path}`;
    const jsonLoader = packModules[key];
    const rawLoader = packRawModules[key];
    if (!jsonLoader || !rawLoader) return null;
    const pack = ((await jsonLoader()) as { default: SectionLapsPack }).default;
    const rawText = (await rawLoader()) as string;
    if ((await sha256Hex(rawText)) !== ref.sha256 || pack.id !== ref.id || pack.sessionId !== sessionId) {
      throw new Error(`Section-lap pack integrity mismatch: ${ref.path}`);
    }
    return pack;
  })();
  cache.set(sessionId, promise);
  return promise;
};
